spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: postgres
    password: ${DB_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
  profiles:
    active: develop

server:
  port: 8080

JWT-SECRET: ${JWT_SECRET}